import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'id_ID': {
          'boarding.action1.title': 'Cari Pekerja',
          'boarding.action1.desc': 'Pesan jasa untuk membantu pekerjaanmu',
          'boarding.action2.title': 'Jadi Pekerja',
          'boarding.action2.desc': 'Bantu orang lain menyelesaikan masalahnya',
          'boarding.agreement.1':
              'Dengan masuk atau mendaftar, kamu menyetujui ',
          'boarding.agreement.terms': 'Ketentuan Layanan',
          'boarding.agreement.2': ' dan ',
          'boarding.agreement.privacy': 'Kebijakan Privasi',
          'boarding.agreement.3': ' kami.',
          'login.welcome': 'Selamat datang kembali',
          'login.employer': 'Temukan pekerja yang cocok untuk kamu!',
          'form.label.phone': 'Nomor Handphone',
          'form.hint.phone': 'Masukkan Nomor Handphone',
          'form.label.password': 'Kata Sandi',
          'form.hint.password': 'Masukkan Kata Sandi',
          'action.forgot_password': 'Lupa kata sandi?',
          'action.employer.login': 'Masuk sebagai Pencari Pekerja',
          'label.dont_have_account': 'Belum punya akun?',
          'action.register': 'Daftar',
          'login.worker': 'Raih penghasilan tambahan bersama Bell Job',
          'action.worker.login': 'Masuk sebagai Pekerja',
          'label.register.title': 'Pendaftaran Akun',
          'label.register.desc': 'Lengkapi form untuk melanjutkan pendaftaran',
          'form.label.full_name': 'Nama Lengkap',
          'form.hint.full_name': 'Masukkan nama lengkap',
          'form.label.password_confirmation': 'Ulangi Kata Sandi',
          'form.hint.password_confirmation': 'Masukkan ulang kata sandi',
          'label.have_account': 'Sudah punya akun?',
          'action.login': 'Masuk',
        },
        'en_US': {
          'boarding.action1.title': 'Looking for Workers',
          'boarding.action1.desc': 'Order services to help your work',
          'boarding.action2.title': 'Become a Worker',
          'boarding.action2.desc': 'Help others solve their problems',
          'boarding.agreement.1':
              'By logging in or registering, you agree to our ',
          'boarding.agreement.terms': 'Terms of Service',
          'boarding.agreement.2': ' and ',
          'boarding.agreement.privacy': 'Privacy Policy',
          'boarding.agreement.3': '.',
          'login.welcome': 'Welcome Back',
          'login.employer': 'Find workers that fit your needs!',
          'form.label.phone': 'Phone Number',
          'form.hint.phone': 'Enter Phone Number',
          'form.label.password': 'Password',
          'form.hint.password': 'Enter Password',
          'action.forgot_password': 'Forgot Password?',
          'action.employer.login': 'Login as Employer',
          'label.dont_have_account': 'Don\'t have an account?',
          'action.register': 'Register',
          'login.worker': 'Earn extra income with Bell Job',
          'action.worker.login': 'Login as Worker',
          'label.register.title': 'Account Registration',
          'label.register.desc': 'Fill in the form to continue registration',
          'form.label.full_name': 'Full Name',
          'form.hint.full_name': 'Enter full name',
          'form.label.password_confirmation': 'Repeat Password',
          'form.hint.password_confirmation': 'Enter password again',
          'label.have_account': 'Already have an account?',
          'action.login': 'Login',
        },
      };
}
